# Generated by Django 5.2.8 on 2026-02-14 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StravaAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("athlete_id", models.BigIntegerField(help_text="Strava athlete ID")),
                (
                    "access_token",
                    models.CharField(help_text="OAuth access token", max_length=255),
                ),
                (
                    "refresh_token",
                    models.CharField(help_text="OAuth refresh token", max_length=255),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(help_text="When the access token expires"),
                ),
                (
                    "athlete_data",
                    models.JSONField(
                        default=dict, help_text="Cached athlete profile data"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Strava Authentication",
                "verbose_name_plural": "Strava Authentications",
            },
        ),
        migrations.CreateModel(
            name="DiscordUserMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discord_user_id",
                    models.BigIntegerField(help_text="Discord user ID", unique=True),
                ),
                (
                    "discord_username",
                    models.CharField(help_text="Discord username", max_length=100),
                ),
                (
                    "discord_display_name",
                    models.CharField(
                        blank=True, help_text="Discord display name", max_length=100
                    ),
                ),
                (
                    "linked_name",
                    models.CharField(
                        blank=True,
                        help_text="Links to RollCallRanking.name",
                        max_length=100,
                    ),
                ),
                (
                    "linked_twitter_handle",
                    models.CharField(
                        blank=True,
                        help_text="Links to RollCallRanking.twitter_handle",
                        max_length=100,
                    ),
                ),
                (
                    "linked_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the link was created"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this mapping is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked Django user account",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discord_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord User Mapping",
                "verbose_name_plural": "Discord User Mappings",
                "ordering": ["discord_username"],
            },
        ),
        migrations.CreateModel(
            name="Attestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("discord", "Discord"),
                            ("telegram", "Telegram"),
                            ("strava", "Strava"),
                        ],
                        default="discord",
                        help_text="Platform where attestation was posted",
                        max_length=10,
                    ),
                ),
                (
                    "discord_message_id",
                    models.BigIntegerField(
                        blank=True, help_text="Discord message ID", null=True
                    ),
                ),
                (
                    "discord_channel_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Discord channel ID where attestation was posted",
                        null=True,
                    ),
                ),
                (
                    "telegram_message_id",
                    models.BigIntegerField(
                        blank=True, help_text="Telegram message ID", null=True
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.BigIntegerField(
                        blank=True, help_text="Telegram chat ID", null=True
                    ),
                ),
                (
                    "part_number",
                    models.IntegerField(
                        default=1, help_text="Part number for multi-part attestations"
                    ),
                ),
                ("raw_text", models.TextField(help_text="Full attestation text")),
                (
                    "posted_at",
                    models.DateTimeField(help_text="When the attestation was posted"),
                ),
                (
                    "has_attachments",
                    models.BooleanField(
                        default=False, help_text="Whether this part has attachments"
                    ),
                ),
                (
                    "attachment_count",
                    models.IntegerField(default=0, help_text="Number of attachments"),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Hidden from review/ranking (soft delete)",
                    ),
                ),
                (
                    "hidden_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the attestation was hidden",
                        null=True,
                    ),
                ),
                (
                    "parsed_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parsed attestation data (for future use)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_attestation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent attestation for multi-part attestations",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="rollcall.attestation",
                    ),
                ),
                (
                    "discord_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attestations",
                        to="rollcall.discordusermapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attestation",
                "verbose_name_plural": "Attestations",
                "ordering": ["-posted_at", "part_number"],
            },
        ),
        migrations.CreateModel(
            name="StravaActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_id",
                    models.BigIntegerField(help_text="Strava activity ID", unique=True),
                ),
                ("name", models.CharField(help_text="Activity name", max_length=255)),
                (
                    "sport_type",
                    models.CharField(
                        help_text="Sport type (Run, Ride, Swim, etc.)", max_length=100
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="Activity start time (UTC)"),
                ),
                (
                    "start_date_local",
                    models.DateTimeField(
                        help_text="Activity start time (local timezone)"
                    ),
                ),
                (
                    "moving_time_seconds",
                    models.IntegerField(help_text="Time spent moving in seconds"),
                ),
                (
                    "elapsed_time_seconds",
                    models.IntegerField(help_text="Total elapsed time in seconds"),
                ),
                (
                    "distance_meters",
                    models.FloatField(
                        blank=True, help_text="Distance in meters", null=True
                    ),
                ),
                (
                    "total_elevation_gain",
                    models.FloatField(
                        blank=True, help_text="Elevation gain in meters", null=True
                    ),
                ),
                (
                    "average_speed",
                    models.FloatField(
                        blank=True, help_text="Average speed in m/s", null=True
                    ),
                ),
                (
                    "max_speed",
                    models.FloatField(
                        blank=True, help_text="Max speed in m/s", null=True
                    ),
                ),
                (
                    "average_heartrate",
                    models.FloatField(
                        blank=True, help_text="Average heart rate", null=True
                    ),
                ),
                (
                    "max_heartrate",
                    models.FloatField(
                        blank=True, help_text="Max heart rate", null=True
                    ),
                ),
                (
                    "average_cadence",
                    models.FloatField(
                        blank=True, help_text="Average cadence", null=True
                    ),
                ),
                (
                    "average_watts",
                    models.FloatField(
                        blank=True, help_text="Average power in watts", null=True
                    ),
                ),
                (
                    "suffer_score",
                    models.IntegerField(
                        blank=True, help_text="Relative effort score", null=True
                    ),
                ),
                (
                    "kudos_count",
                    models.IntegerField(default=0, help_text="Number of kudos"),
                ),
                (
                    "raw_data",
                    models.JSONField(default=dict, help_text="Full API response"),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "strava_auth",
                    models.ForeignKey(
                        help_text="Strava auth this activity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="rollcall.stravaauth",
                    ),
                ),
            ],
            options={
                "verbose_name": "Strava Activity",
                "verbose_name_plural": "Strava Activities",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TelegramUserMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_user_id",
                    models.BigIntegerField(help_text="Telegram user ID", unique=True),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True, help_text="Telegram username", max_length=100
                    ),
                ),
                (
                    "telegram_first_name",
                    models.CharField(help_text="Telegram first name", max_length=100),
                ),
                (
                    "telegram_last_name",
                    models.CharField(
                        blank=True, help_text="Telegram last name", max_length=100
                    ),
                ),
                (
                    "linked_name",
                    models.CharField(
                        blank=True,
                        help_text="Links to RollCallRanking.name",
                        max_length=100,
                    ),
                ),
                (
                    "linked_twitter_handle",
                    models.CharField(
                        blank=True,
                        help_text="Links to RollCallRanking.twitter_handle",
                        max_length=100,
                    ),
                ),
                (
                    "linked_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the link was created"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this mapping is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked Django user account",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telegram_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram User Mapping",
                "verbose_name_plural": "Telegram User Mappings",
                "ordering": ["telegram_first_name", "telegram_username"],
            },
        ),
        migrations.AddField(
            model_name="stravaauth",
            name="telegram_user",
            field=models.OneToOneField(
                help_text="Telegram user who linked this Strava account",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="strava_auth",
                to="rollcall.telegramusermapping",
            ),
        ),
        migrations.CreateModel(
            name="MessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("discord", "Discord"), ("telegram", "Telegram")],
                        help_text="Platform where message was posted",
                        max_length=10,
                    ),
                ),
                (
                    "discord_message_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Discord message ID",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "discord_channel_id",
                    models.BigIntegerField(
                        blank=True, help_text="Discord channel ID", null=True
                    ),
                ),
                (
                    "telegram_message_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Telegram message ID",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.BigIntegerField(
                        blank=True, help_text="Telegram chat ID", null=True
                    ),
                ),
                ("content", models.TextField(help_text="Message content")),
                (
                    "posted_at",
                    models.DateTimeField(help_text="When the message was posted"),
                ),
                (
                    "has_attachments",
                    models.BooleanField(
                        default=False, help_text="Whether message has attachments"
                    ),
                ),
                (
                    "attachment_count",
                    models.IntegerField(default=0, help_text="Number of attachments"),
                ),
                (
                    "attachment_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Details about attachments (file IDs, names, types, etc.)",
                    ),
                ),
                (
                    "is_attestation",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this message was converted to an attestation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attestation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Attestation created from this message",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_messages",
                        to="rollcall.attestation",
                    ),
                ),
                (
                    "discord_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_logs",
                        to="rollcall.discordusermapping",
                    ),
                ),
                (
                    "telegram_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_logs",
                        to="rollcall.telegramusermapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Log",
                "verbose_name_plural": "Message Logs",
                "ordering": ["-posted_at"],
            },
        ),
        migrations.AddField(
            model_name="attestation",
            name="telegram_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attestations",
                to="rollcall.telegramusermapping",
            ),
        ),
        migrations.CreateModel(
            name="WebLoginToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Random login token", max_length=32, unique=True
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False, help_text="Whether token has been used for login"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When user confirmed via Telegram",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this token expires"),
                ),
                (
                    "telegram_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Telegram user who confirmed this token",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rollcall.telegramusermapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "Web Login Token",
                "verbose_name_plural": "Web Login Tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeeklyRollCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start_date", models.DateField(help_text="Monday of the week")),
                ("week_end_date", models.DateField(help_text="Sunday of the week")),
                ("substack_url", models.URLField(help_text="Link to Substack post")),
                (
                    "full_text",
                    models.TextField(
                        help_text="Complete Substack post text (unlimited length)"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this roll call has been officially published.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Weekly Roll Call",
                "verbose_name_plural": "Weekly Roll Calls",
                "ordering": ["-week_start_date"],
                "unique_together": {("week_start_date",)},
            },
        ),
        migrations.CreateModel(
            name="RollCallRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        help_text="Position in rankings (1, 2, 3, etc.)"
                    ),
                ),
                ("name", models.CharField(help_text="Display name", max_length=100)),
                (
                    "twitter_handle",
                    models.CharField(
                        blank=True,
                        help_text="Twitter/X handle (without @)",
                        max_length=100,
                    ),
                ),
                (
                    "weekly_roll_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rankings",
                        to="rollcall.weeklyrollcall",
                    ),
                ),
            ],
            options={
                "verbose_name": "Roll Call Ranking",
                "verbose_name_plural": "Roll Call Rankings",
                "ordering": ["rank"],
            },
        ),
        migrations.CreateModel(
            name="RankingTrial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trial_number",
                    models.IntegerField(
                        help_text="Sequential trial number for the week"
                    ),
                ),
                (
                    "ai_provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("grok", "Grok"),
                            ("deepseek", "DeepSeek"),
                        ],
                        help_text="AI provider used",
                        max_length=20,
                    ),
                ),
                (
                    "ai_model",
                    models.CharField(
                        help_text="Specific model used (e.g., 'gpt-4', 'claude-3-opus')",
                        max_length=100,
                    ),
                ),
                (
                    "raw_response",
                    models.TextField(help_text="Full API response for debugging"),
                ),
                (
                    "parsed_rankings",
                    models.JSONField(default=list, help_text="Parsed ranking data"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "weekly_roll_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranking_trials",
                        to="rollcall.weeklyrollcall",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ranking Trial",
                "verbose_name_plural": "Ranking Trials",
                "ordering": ["trial_number"],
            },
        ),
        migrations.AddField(
            model_name="attestation",
            name="weekly_roll_call",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attestations",
                to="rollcall.weeklyrollcall",
            ),
        ),
        migrations.AddIndex(
            model_name="discordusermapping",
            index=models.Index(
                fields=["linked_name"], name="rollcall_di_linked__ff5c82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discordusermapping",
            index=models.Index(
                fields=["linked_twitter_handle"], name="rollcall_di_linked__daab17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discordusermapping",
            index=models.Index(
                fields=["is_active"], name="rollcall_di_is_acti_8787c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discordusermapping",
            index=models.Index(fields=["user"], name="rollcall_di_user_id_f0f78a_idx"),
        ),
        migrations.AddIndex(
            model_name="stravaactivity",
            index=models.Index(
                fields=["strava_auth", "start_date"],
                name="rollcall_st_strava__37809a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stravaactivity",
            index=models.Index(
                fields=["sport_type"], name="rollcall_st_sport_t_0cdbfc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="telegramusermapping",
            index=models.Index(
                fields=["linked_name"], name="rollcall_te_linked__9a60c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="telegramusermapping",
            index=models.Index(
                fields=["linked_twitter_handle"], name="rollcall_te_linked__1f412c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="telegramusermapping",
            index=models.Index(
                fields=["is_active"], name="rollcall_te_is_acti_bdb0ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="telegramusermapping",
            index=models.Index(fields=["user"], name="rollcall_te_user_id_362250_idx"),
        ),
        migrations.AddIndex(
            model_name="messagelog",
            index=models.Index(
                fields=["source", "posted_at"], name="rollcall_me_source_7098f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagelog",
            index=models.Index(
                fields=["discord_user", "posted_at"],
                name="rollcall_me_discord_764d46_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagelog",
            index=models.Index(
                fields=["telegram_user", "posted_at"],
                name="rollcall_me_telegra_cc66d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagelog",
            index=models.Index(
                fields=["source", "discord_message_id"],
                name="rollcall_me_source_e27a21_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagelog",
            index=models.Index(
                fields=["source", "telegram_message_id"],
                name="rollcall_me_source_0fd289_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagelog",
            index=models.Index(
                fields=["is_attestation"], name="rollcall_me_is_atte_d48874_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagelog",
            index=models.Index(
                fields=["posted_at"], name="rollcall_me_posted__5cbb74_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="messagelog",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("discord_message_id__isnull", False), ("source", "discord")
                ),
                fields=("source", "discord_message_id"),
                name="unique_discord_message_log",
            ),
        ),
        migrations.AddConstraint(
            model_name="messagelog",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("source", "telegram"), ("telegram_message_id__isnull", False)
                ),
                fields=("source", "telegram_message_id"),
                name="unique_telegram_message_log",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rollcallranking",
            unique_together={("weekly_roll_call", "rank")},
        ),
        migrations.AddIndex(
            model_name="rankingtrial",
            index=models.Index(
                fields=["weekly_roll_call", "trial_number"],
                name="rollcall_ra_weekly__fb1552_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rankingtrial",
            index=models.Index(
                fields=["weekly_roll_call"], name="rollcall_ra_weekly__db881f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rankingtrial",
            index=models.Index(
                fields=["trial_number"], name="rollcall_ra_trial_n_b84afd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rankingtrial",
            unique_together={("weekly_roll_call", "trial_number")},
        ),
        migrations.AddIndex(
            model_name="attestation",
            index=models.Index(
                fields=["weekly_roll_call", "posted_at"],
                name="rollcall_at_weekly__3d1482_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attestation",
            index=models.Index(
                fields=["discord_user", "posted_at"],
                name="rollcall_at_discord_35cc05_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attestation",
            index=models.Index(
                fields=["telegram_user", "posted_at"],
                name="rollcall_at_telegra_f21ecb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attestation",
            index=models.Index(
                fields=["source", "discord_message_id"],
                name="rollcall_at_source_2c6457_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attestation",
            index=models.Index(
                fields=["source", "telegram_message_id"],
                name="rollcall_at_source_25b17f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attestation",
            index=models.Index(
                fields=["parent_attestation", "part_number"],
                name="rollcall_at_parent__976c51_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attestation",
            index=models.Index(
                fields=["is_hidden"], name="rollcall_at_is_hidd_b83490_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="attestation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("discord_message_id__isnull", False), ("source", "discord")
                ),
                fields=("source", "discord_message_id"),
                name="unique_discord_message",
            ),
        ),
        migrations.AddConstraint(
            model_name="attestation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("source", "telegram"), ("telegram_message_id__isnull", False)
                ),
                fields=("source", "telegram_message_id"),
                name="unique_telegram_message",
            ),
        ),
    ]
