# Generated by Django 5.2.8 on 2026-02-22 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rollcall", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractedMetrics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                ("model_used", models.CharField(max_length=100)),
                ("raw_response", models.JSONField(default=dict)),
                ("daily_steps", models.IntegerField(blank=True, null=True)),
                ("calories_burned", models.IntegerField(blank=True, null=True)),
                ("resting_heart_rate", models.IntegerField(blank=True, null=True)),
                ("vo2_max", models.FloatField(blank=True, null=True)),
                ("sleep_hours", models.FloatField(blank=True, null=True)),
                ("body_weight", models.FloatField(blank=True, null=True)),
                ("body_fat_pct", models.FloatField(blank=True, null=True)),
                ("strength_sessions", models.IntegerField(blank=True, null=True)),
                ("cardio_sessions", models.IntegerField(blank=True, null=True)),
                ("combat_sessions", models.IntegerField(blank=True, null=True)),
                ("total_training_sessions", models.IntegerField(blank=True, null=True)),
                ("protein_grams", models.IntegerField(blank=True, null=True)),
                ("calories_consumed", models.IntegerField(blank=True, null=True)),
                ("bench_press", models.FloatField(blank=True, null=True)),
                ("squat", models.FloatField(blank=True, null=True)),
                ("deadlift", models.FloatField(blank=True, null=True)),
                ("extra_metrics", models.JSONField(blank=True, default=dict)),
                ("extraction_error", models.TextField(blank=True, default="")),
                ("last_extraction_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attestation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="metrics", to="rollcall.attestation"
                    ),
                ),
            ],
            options={
                "verbose_name": "Extracted Metrics",
                "verbose_name_plural": "Extracted Metrics",
                "indexes": [models.Index(fields=["attestation"], name="rollcall_ex_attesta_51119a_idx")],
            },
        ),
    ]
