# Generated by Django 5.2.7 on 2026-05-05 17:05
#
# Phase 0 of the binary-juggling-locket conversational bot upgrade:
#   - New ChatContextReset model (single mechanism for /forget cutoffs)
#   - New MessageLog fields: is_bot_reply, classifier_verdict, kind
#   - Composite (chat_id, message_id) dedupe on MessageLog and Attestation
#     for telegram rows (Telegram message_id is unique only within a chat)
#
# The collision-detection step at the top of operations[] surfaces any
# pre-existing duplicate (chat_id, message_id) pairs BEFORE the new unique
# constraints are added — a partial-index migration would otherwise fail
# silently on a duplicate insert at runtime later. Expected count: 0,
# because DM volume has been near-zero historically.

import django.db.models.deletion
from django.db import migrations, models


def detect_telegram_id_collisions(apps, schema_editor):
    """Surface any rows that would violate the new composite uniqueness.

    For both MessageLog and Attestation, count groups of telegram rows
    sharing the same (telegram_chat_id, telegram_message_id). Any group
    with size > 1 will block the new constraint at insert time later.

    Raises a clear error listing the colliding rows; otherwise no-op.
    Migration is rolled back if collisions are found, so the operator
    can inspect and clean up before retrying.
    """
    from django.db.models import Count

    MessageLog = apps.get_model("rollcall", "MessageLog")
    Attestation = apps.get_model("rollcall", "Attestation")

    problems = []

    for model in (MessageLog, Attestation):
        dupes = (
            model.objects.filter(source="telegram", telegram_message_id__isnull=False)
            .values("telegram_chat_id", "telegram_message_id")
            .annotate(n=Count("id"))
            .filter(n__gt=1)
            .order_by("-n")[:50]
        )
        for row in dupes:
            problems.append(
                f"{model.__name__}: chat={row['telegram_chat_id']} "
                f"msg={row['telegram_message_id']} count={row['n']}"
            )

    if problems:
        raise RuntimeError(
            "Phase 0 migration: pre-existing duplicate (chat_id, message_id) "
            "rows would violate the new composite uniqueness. Resolve before "
            "retrying. First 50:\n  " + "\n  ".join(problems)
        )


class Migration(migrations.Migration):

    dependencies = [
        ("rollcall", "0002_add_extracted_metrics"),
    ]

    operations = [
        migrations.RunPython(
            detect_telegram_id_collisions,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="ChatContextReset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("discord", "Discord")],
                        default="telegram",
                        help_text="Platform",
                        max_length=10,
                    ),
                ),
                ("chat_id", models.BigIntegerField(help_text="Telegram chat ID or Discord channel ID")),
                (
                    "cutoff_at",
                    models.DateTimeField(help_text="Messages with posted_at <= cutoff_at are hidden from bot context"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Chat Context Reset",
                "verbose_name_plural": "Chat Context Resets",
                "ordering": ["-cutoff_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="attestation",
            name="unique_telegram_message",
        ),
        migrations.RemoveConstraint(
            model_name="messagelog",
            name="unique_telegram_message_log",
        ),
        migrations.RemoveIndex(
            model_name="attestation",
            name="rollcall_at_source_25b17f_idx",
        ),
        migrations.RemoveIndex(
            model_name="messagelog",
            name="rollcall_me_source_0fd289_idx",
        ),
        migrations.AddField(
            model_name="messagelog",
            name="classifier_verdict",
            field=models.JSONField(
                blank=True,
                help_text="Sonnet classifier output (Phase A) — {is_attestation, should_reply, intent, ...}",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="messagelog",
            name="is_bot_reply",
            field=models.BooleanField(
                db_index=True, default=False, help_text="True for messages the bot itself sent (vs warrior-authored)"
            ),
        ),
        migrations.AddField(
            model_name="messagelog",
            name="kind",
            field=models.CharField(
                default="warrior",
                help_text="Row purpose: 'warrior', 'reply', 'attestation_ack', 'command_reply', 'error', 'private_files_listing', etc.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="messagelog",
            name="telegram_message_id",
            field=models.BigIntegerField(
                blank=True, help_text="Telegram message ID (unique within a chat, not globally)", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="attestation",
            index=models.Index(
                fields=["source", "telegram_chat_id", "telegram_message_id"], name="rollcall_at_source_ca37db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagelog",
            index=models.Index(
                fields=["source", "telegram_chat_id", "telegram_message_id"], name="rollcall_me_source_c9766a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="attestation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("source", "telegram"), ("telegram_chat_id__isnull", False), ("telegram_message_id__isnull", False)
                ),
                fields=("source", "telegram_chat_id", "telegram_message_id"),
                name="unique_telegram_chat_message",
            ),
        ),
        migrations.AddConstraint(
            model_name="messagelog",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("source", "telegram"), ("telegram_chat_id__isnull", False), ("telegram_message_id__isnull", False)
                ),
                fields=("source", "telegram_chat_id", "telegram_message_id"),
                name="unique_telegram_chat_message_log",
            ),
        ),
        migrations.AddField(
            model_name="chatcontextreset",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who issued /forget",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="context_resets",
                to="rollcall.telegramusermapping",
            ),
        ),
        migrations.AddIndex(
            model_name="chatcontextreset",
            index=models.Index(fields=["source", "chat_id", "-cutoff_at"], name="rollcall_ch_source_561e1a_idx"),
        ),
    ]
