# Generated by Django 5.2.8 on 2026-08-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rollcall", "0003_chatcontextreset_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weeklyrollcall",
            name="substack_url",
            field=models.URLField(help_text="Canonical Roll Call URL (legacy field name)"),
        ),
        migrations.AlterField(
            model_name="weeklyrollcall",
            name="full_text",
            field=models.TextField(help_text="Complete Roll Call markdown (unlimited length)"),
        ),
    ]
