# Generated by Django 5.0.1 on 2025-11-10 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="active", max_length=20)),
                ("notes", models.TextField(blank=True, null=True)),
                ("notes_generated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_sessions",
                        to="bot.discordchannel",
                    ),
                ),
            ],
            options={
                "db_table": "voice_sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="VoiceTranscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("timestamp", models.DateTimeField()),
                ("duration", models.FloatField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcriptions",
                        to="bot.voicesession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voice_transcriptions",
                        to="bot.discorduser",
                    ),
                ),
            ],
            options={
                "db_table": "voice_transcriptions",
                "ordering": ["timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="voicesession",
            index=models.Index(
                fields=["channel", "started_at"], name="voice_sessi_channel_ae16b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voicesession",
            index=models.Index(fields=["status"], name="voice_sessi_status_08d503_idx"),
        ),
        migrations.AddIndex(
            model_name="voicetranscription",
            index=models.Index(
                fields=["session", "timestamp"], name="voice_trans_session_28eee3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voicetranscription",
            index=models.Index(
                fields=["user", "timestamp"], name="voice_trans_user_id_8e21ff_idx"
            ),
        ),
    ]
