# Generated by Django 5.2.7 on 2026-05-25 11:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rollcall", "0003_chatcontextreset_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("questions", models.JSONField(help_text='List of {"key": str, "label": str} dicts')),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("baseline", "Baseline (Stronger in 60)"),
                            ("ai_mutation", "AI mutation"),
                            ("user_reset", "User reset to baseline"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_current", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "derived_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="descendants",
                        to="daily.checklistversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyParticipant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("display_name", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("warrior", "Warrior (bridged from rollcall)"),
                            ("external", "External (token-authenticated)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "telegram_mapping",
                    models.ForeignKey(
                        blank=True,
                        help_text="Populated for warriors; null for external participants",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_participants",
                        to="rollcall.telegramusermapping",
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="DailyCheckIn",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("comment", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(choices=[("web", "Web"), ("telegram", "Telegram")], default="web", max_length=20),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checklist_version",
                    models.ForeignKey(
                        help_text="Which checklist was active on this date",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkins",
                        to="daily.checklistversion",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="daily.dailyparticipant",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "participant_id"],
            },
        ),
        migrations.CreateModel(
            name="DailyAccessToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_tokens",
                        to="daily.dailyparticipant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="checklistversion",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checklist_versions",
                to="daily.dailyparticipant",
            ),
        ),
        migrations.CreateModel(
            name="CoachSuggestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("suggestion_text", models.TextField()),
                (
                    "proposed_questions",
                    models.JSONField(
                        blank=True, help_text="Optional new question list to auto-apply tomorrow", null=True
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("shown", "Shown"),
                            ("acknowledged", "Acknowledged"),
                            ("dismissed", "Dismissed"),
                            ("applied", "Mutation applied"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("cost_usd", models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applied_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_from_suggestions",
                        to="daily.checklistversion",
                    ),
                ),
                (
                    "check_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="suggestions", to="daily.dailycheckin"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["check_in", "status"], name="daily_coach_check_i_89ff5f_idx")],
            },
        ),
        migrations.CreateModel(
            name="DailyCheckInAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question_key", models.CharField(max_length=40)),
                ("value", models.BooleanField(default=False)),
                (
                    "check_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="daily.dailycheckin"
                    ),
                ),
            ],
            options={
                "ordering": ["check_in", "question_key"],
                "unique_together": {("check_in", "question_key")},
            },
        ),
        migrations.AddIndex(
            model_name="dailyparticipant",
            index=models.Index(fields=["kind", "is_active"], name="daily_daily_kind_ff2464_idx"),
        ),
        migrations.AddIndex(
            model_name="dailycheckin",
            index=models.Index(fields=["participant", "-date"], name="daily_daily_partici_755243_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="dailycheckin",
            unique_together={("participant", "date")},
        ),
        migrations.AddConstraint(
            model_name="checklistversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("participant",),
                name="one_current_checklist_per_participant",
            ),
        ),
    ]
