# Generated by Django 5.2.7 on 2026-06-09 19:01
# Hand-edited: add `state` FIRST, copy value→state, THEN drop `value`.

from django.db import migrations, models


def value_to_state(apps, schema_editor):
    Answer = apps.get_model("daily", "DailyCheckInAnswer")
    Answer.objects.filter(value=True).update(state="done")
    Answer.objects.filter(value=False).update(state="pending")


def state_to_value(apps, schema_editor):
    Answer = apps.get_model("daily", "DailyCheckInAnswer")
    Answer.objects.filter(state="done").update(value=True)
    Answer.objects.exclude(state="done").update(value=False)


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailycheckinanswer",
            name="state",
            field=models.CharField(
                choices=[("pending", "Pending"), ("done", "Done"), ("skip", "Skipped")],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.RunPython(value_to_state, state_to_value),
        migrations.RemoveField(
            model_name="dailycheckinanswer",
            name="value",
        ),
        migrations.AddField(
            model_name="checklistversion",
            name="bonus_questions",
            field=models.JSONField(
                blank=True, help_text="Optional extra-credit items for the day; never counted in score", null=True
            ),
        ),
        migrations.AddField(
            model_name="coachsuggestion",
            name="proposed_bonus",
            field=models.JSONField(blank=True, help_text="Optional extra-credit items for tomorrow (0-3)", null=True),
        ),
    ]
