# Generated by Django 5.2.7 on 2026-06-19 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0002_remove_dailycheckinanswer_value_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("endpoint", models.URLField(max_length=500, unique=True)),
                ("p256dh", models.CharField(max_length=200)),
                ("auth", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_pushed_at", models.DateTimeField(blank=True, null=True)),
                ("fail_count", models.IntegerField(default=0)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to="daily.dailyparticipant",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["participant"], name="daily_pushs_partici_3b7fa2_idx")],
            },
        ),
    ]
