# Generated by Django 5.2.7 on 2026-06-22 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0003_pushsubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMetric",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=40)),
                ("label", models.CharField(max_length=60)),
                ("unit", models.CharField(blank=True, max_length=12)),
                (
                    "kind",
                    models.CharField(
                        choices=[("number", "Number"), ("scale", "Scale (0-10)")], default="number", max_length=10
                    ),
                ),
                ("has_am_pm", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="metrics", to="daily.dailyparticipant"
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "unique_together": {("participant", "key")},
            },
        ),
        migrations.CreateModel(
            name="DailyMetricReading",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("slot", models.CharField(default="", max_length=2)),
                ("value", models.DecimalField(decimal_places=2, max_digits=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="readings", to="daily.dailymetric"
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "indexes": [models.Index(fields=["metric", "date"], name="daily_daily_metric__9c96c6_idx")],
                "unique_together": {("metric", "date", "slot")},
            },
        ),
    ]
