# Generated by Django 5.2.8 on 2026-06-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0005_coachchatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyparticipant",
            name="timezone",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
