# Generated by Django 5.2.8 on 2026-06-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0006_participant_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="pushsubscription",
            name="last_badge_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
