# Generated by Django 5.2.8 on 2026-06-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0007_pushsubscription_last_badge_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyparticipant",
            name="onboarded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyparticipant",
            name="source",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="dailyparticipant",
            name="source_detail",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
