# Generated by Django 5.2.8 on 2026-07-02 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0008_participant_source_onboarding"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("profile_text", models.TextField()),
                ("source_hash", models.CharField(blank=True, default="", max_length=64)),
                ("attestation_count", models.IntegerField(default=0)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("cost_usd", models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_profile",
                        to="daily.dailyparticipant",
                    ),
                ),
            ],
        ),
    ]
