# Generated by Django 5.2.8 on 2026-07-02 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0009_coachprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyparticipant",
            name="morning_target_hour",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Manual override (local hour, 0-23) for the morning coach-note/badge push — overrides the learned wake-hour estimate. 20-23 = push the evening before, for the next local day. Blank = learn from activity history (fallback 6am).",
                null=True,
                validators=[django.core.validators.MaxValueValidator(23)],
            ),
        ),
    ]
