# Generated by Django 5.2.7 on 2026-07-02 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0010_dailyparticipant_morning_target_hour"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyparticipant",
            name="evening_nudge_hour",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Manual override (local hour, 0-23) for the evening 'Plan tomorrow' nudge push. Blank = default (22 / 10pm local).",
                null=True,
                validators=[django.core.validators.MaxValueValidator(23)],
            ),
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="last_evening_nudge_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
