# Generated by Django 5.2.16 on 2026-07-09 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0011_dailyparticipant_evening_nudge_hour_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyparticipant",
            name="ai_mutations_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Let Jamie adjust the checklist overnight (beta only). Off = support-only Jamie who never edits the list.",
            ),
        ),
        migrations.AddField(
            model_name="dailyparticipant",
            name="beta",
            field=models.BooleanField(
                default=False,
                help_text="Show the new Climb experience (combined win+habit screen, narrowed Jamie). False = today's app, untouched.",
            ),
        ),
        migrations.AddField(
            model_name="dailyparticipant",
            name="focus",
            field=models.CharField(
                blank=True,
                choices=[("health", "Health"), ("life", "Life")],
                default="",
                help_text="Beta: soft health/life focus set in onboarding.",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="WinItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=200)),
                ("scoped_label", models.CharField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("done", "Done"), ("graduated", "Graduated to habit")],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("surfaced_on", models.DateField(blank=True, null=True)),
                ("deferred_on", models.DateField(blank=True, null=True)),
                ("defer_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="wins", to="daily.dailyparticipant"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "indexes": [
                    models.Index(fields=["participant", "status"], name="daily_winit_partici_ff0d43_idx"),
                    models.Index(fields=["participant", "surfaced_on"], name="daily_winit_partici_526cf7_idx"),
                ],
            },
        ),
    ]
