# Generated by Django 5.2.16 on 2026-07-09 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0012_dailyparticipant_ai_mutations_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="winitem",
            name="is_goal",
            field=models.BooleanField(
                default=False, help_text="True = a north star that owns stepping stones; never surfaced on its own."
            ),
        ),
        migrations.AddField(
            model_name="winitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The north star this stepping stone belongs to (null for standalone wins and for north stars themselves).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stones",
                to="daily.winitem",
            ),
        ),
    ]
