# Generated by Django 5.2.16 on 2026-07-10 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0013_winitem_is_goal_winitem_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="winitem",
            name="scoped_label",
        ),
    ]
