# Generated by Django 5.2.16 on 2026-07-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0014_remove_winitem_scoped_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailycheckinanswer",
            name="derived",
            field=models.BooleanField(default=False),
        ),
    ]
