# Generated by Django 5.2.16 on 2026-07-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0015_dailycheckinanswer_derived"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachsuggestion",
            name="base_questions",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
