"""Tag pre-category bonus items as health so they survive the beta filter.

The beta dashboard and set_item_state now only accept bonus items with
category == "health" (services/checklist.health_bonus_items — an explicit
tag, no wording heuristics). Every bonus that exists before this branch was
generated by the health-only coach, so the tag is factually correct; without
it those items vanish from the page and their taps return 400 bad_key.
"""
from django.db import migrations


def tag_legacy_bonuses(apps, schema_editor):
    ChecklistVersion = apps.get_model("daily", "ChecklistVersion")
    for version in ChecklistVersion.objects.exclude(bonus_questions=None).iterator():
        changed = False
        for item in version.bonus_questions or []:
            if isinstance(item, dict) and "category" not in item:
                item["category"] = "health"
                changed = True
        if changed:
            version.save(update_fields=["bonus_questions"])


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0019_streak_cache"),
    ]

    operations = [
        migrations.RunPython(tag_legacy_bonuses, migrations.RunPython.noop),
    ]
