# Generated by Django 5.2.16 on 2026-07-18 11:37

from django.db import migrations, models


def grandfather_existing(apps, schema_editor):
    """Every participant that exists at this point migrated from the frozen
    app, so grandfather them into all three legacy health conveniences (they
    had them before beta). Participants created AFTER this migration keep the
    NULL default: native beta users who never see the config gear."""
    DailyParticipant = apps.get_model("daily", "DailyParticipant")
    DailyParticipant.objects.filter(legacy_health_config__isnull=True).update(
        legacy_health_config={"auto_bonus": True, "coach_note": True, "reset": True}
    )


def clear_grandfather(apps, schema_editor):
    DailyParticipant = apps.get_model("daily", "DailyParticipant")
    DailyParticipant.objects.update(legacy_health_config=None)


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0021_tag_remaining_bonus_health"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyparticipant",
            name="legacy_health_config",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(grandfather_existing, clear_grandfather),
    ]
