# Generated by Django 5.2.16 on 2026-07-20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0023_tag_post_grandfather_bonus_health"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyBetaRollout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rollout_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("rolled_back", "Rolled back"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        help_text=(
                            "Original beta/AI/focus flags for every participant "
                            "in this cohort"
                        )
                    ),
                ),
                ("target_count", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField()),
                ("rolled_back_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="dailyparticipant",
            name="beta",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Show the new Climb experience (combined win+habit screen, "
                    "narrowed Jamie). False = temporary legacy fallback."
                ),
            ),
        ),
    ]
